const Skills = () => {
    return (
        <div>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
           <p> Skills</p>
        </div>
    );
}

export default Skills;
